[window]
opacity = 0.85

[scrolling]
history = 10_000

[font]
size = 11

  [font.normal]
  family = "monospace"
  style = "Regular"

  [font.bold]
  family = "monospace"
  style = "Bold"

  [font.italic]
  family = "monospace"
  style = "Italic"

  [font.bold_italic]
  family = "monospace"
  style = "Bold Italic"

[colors.primary]
background = "#1d1f21"
foreground = "#c5c8c6"

[colors.normal]
black = "#1d1f21"
red = "#cc6666"
green = "#b5cd68"
yellow = "#f0c674"
blue = "#5182de"
magenta = "#b294bb"
cyan = "#8abeb7"
white = "#c5c8c6"

[colors.bright]
black = "#666666"
red = "#d54e53"
green = "#b9ca4a"
yellow = "#e7c547"
blue = "#7aa6da"
magenta = "#c397d8"
cyan = "#70c0b1"
white = "#eaeaea"

[colors.dim]
black = "#131415"
red = "#864343"
green = "#777c44"
yellow = "#9e824c"
blue = "#556a7d"
magenta = "#75617b"
cyan = "#5b7d78"
white = "#828482"

[shell]
program = "/usr/bin/tmux"
args = [ "new-session", "-D" ]
